// Generated by `pnpm idl:sync` from target/idl/rostr_escrow.json.
//
// Do not edit by hand. This is the program's interface as the toolchain emitted
// it; editing it here would make the client disagree with the deployed program
// while looking perfectly reasonable in review.

/**
 * A deliberately shallow type for the runtime value. The full shape is large and
 * recursive, and spelling it out would cost compile time to describe something
 * Anchor validates at runtime anyway — `RostrEscrow` in ./types.ts is the type
 * that actually earns its keep.
 */
export type EscrowIdl = {
  readonly address: string;
  readonly metadata: {
    readonly name: string;
    readonly version: string;
    readonly spec: string;
    readonly [key: string]: unknown;
  };
  readonly instructions: readonly unknown[];
  readonly accounts: readonly unknown[];
  readonly errors: readonly unknown[];
  readonly types: readonly unknown[];
};

export const ESCROW_IDL: EscrowIdl = {
  "address": "FtXXoS8G6N3dmhijp2kZGpmX6GmNtDk6cGj9h7eoK5NC",
  "metadata": {
    "name": "rostr_escrow",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Escrow for rostr league pots — deposits, timelock refund, and settlement"
  },
  "instructions": [
    {
      "name": "deposit",
      "docs": [
        "Stake the buy-in.",
        "",
        "Takes no amount. The figure is `league.buy_in` and nothing else, so",
        "\"everyone deposits the identical amount\" (docs/RULES.md § 7) is",
        "structural rather than a check that could be reordered away. A member",
        "who wants to stake more has no instruction that lets them."
      ],
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "League"
              }
            ]
          }
        },
        {
          "name": "membership",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  101,
                  109,
                  98,
                  101,
                  114,
                  115,
                  104,
                  105,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "league"
              },
              {
                "kind": "account",
                "path": "member"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "member_token_account",
          "docs": [
            "The member's own token account. Constraining the mint here is what",
            "BUILD-PLAN calls rejecting mixed tokens \"at the type level\": a deposit in",
            "the wrong token fails account resolution before any handler runs."
          ],
          "writable": true
        },
        {
          "name": "member",
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "initialize_free_league",
      "docs": [
        "Anchor the rules of a league that plays for nothing.",
        "",
        "A free league has no vault, no buy-in, and no payout — but its rule set",
        "is hashed on-chain exactly like a pot league's, and members accept it the",
        "same way through `join_league`. That is the point: \"the rules are",
        "immutable and you can verify them\" has to be true of every league, not",
        "only the ones with money in them. Otherwise a free league's guarantee is",
        "our database, which is the thing this project exists not to ask anyone to",
        "trust.",
        "",
        "Separate from `initialize_league` rather than a flag on it because the",
        "account set genuinely differs: there is no mint and no vault to create,",
        "and making them optional would mean a caller could pass `None` to a pot",
        "league and get a league that can never take a deposit."
      ],
      "discriminator": [
        45,
        128,
        109,
        8,
        49,
        140,
        174,
        112
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "arg",
                "path": "args.league_id"
              }
            ]
          }
        },
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "args",
          "type": {
            "defined": {
              "name": "InitializeFreeLeagueArgs"
            }
          }
        }
      ]
    },
    {
      "name": "initialize_league",
      "docs": [
        "Create the on-chain record of a league, freeze its terms, and open its",
        "vault.",
        "",
        "Everything validated here is validated again off-chain by",
        "`validateRules()` before a league is written to Postgres. The duplication",
        "is deliberate: the off-chain check produces good error messages for a",
        "league creator, and this one is what actually binds, because it is the",
        "only one an attacker cannot skip by calling the program directly."
      ],
      "discriminator": [
        222,
        3,
        239,
        48,
        195,
        8,
        143,
        93
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "arg",
                "path": "args.league_id"
              }
            ]
          }
        },
        {
          "name": "mint"
        },
        {
          "name": "vault",
          "docs": [
            "The pot. A PDA token account whose authority is the league PDA, so no",
            "key held by any person can move what is in it — only this program can,",
            "and only through the instructions below."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "payer",
          "docs": [
            "Pays rent. Holds no privileges afterwards — creating a league is not a",
            "role, and this key is not recorded on the account."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "args",
          "type": {
            "defined": {
              "name": "InitializeLeagueArgs"
            }
          }
        }
      ]
    },
    {
      "name": "join_league",
      "docs": [
        "Join a league by accepting its rules hash.",
        "",
        "The caller passes the hash **they** believe they are agreeing to, and",
        "the program requires it to equal the league's. That is what makes",
        "consent provable rather than asserted: a client that displayed one rule",
        "set cannot enrol someone under another, because the signature is over a",
        "transaction naming the hash. A boolean \"I agree\" would prove only that",
        "somebody clicked something."
      ],
      "discriminator": [
        32,
        4,
        179,
        25,
        65,
        34,
        15,
        127
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "League"
              }
            ]
          }
        },
        {
          "name": "membership",
          "docs": [
            "Seeded by league and member, so one member cannot hold two places in the",
            "same league: the second `join_league` collides with an existing account",
            "rather than needing a check that could be forgotten."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  101,
                  109,
                  98,
                  101,
                  114,
                  115,
                  104,
                  105,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "league"
              },
              {
                "kind": "account",
                "path": "member"
              }
            ]
          }
        },
        {
          "name": "member",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "rules_hash",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "payout_fee",
      "docs": [
        "Pay the protocol fee out of the vault, once.",
        "",
        "Runs before the per-prize payments. The fee is `total * fee_bps / 10000`,",
        "taken from the whole pot, and sent to `league.fee_recipient`. Idempotent:",
        "a second call sees `fee_paid == true` and refuses. Skipped entirely when",
        "`fee_bps == 0`."
      ],
      "discriminator": [
        45,
        126,
        145,
        147,
        97,
        0,
        233,
        103
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "League"
              }
            ]
          }
        },
        {
          "name": "standings",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  116,
                  97,
                  110,
                  100,
                  105,
                  110,
                  103,
                  115
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "fee_recipient_token_account",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "payout_prize",
      "docs": [
        "Pay one prize out of the vault.",
        "",
        "`prize_index` is a `prize` constant (0 = champion … 4 = third place). The",
        "winner is read from the frozen `FinalStandings`, so the authority cannot",
        "redirect a prize to anyone else, and the recipient must be a `Membership`",
        "of this league. The amount is the post-fee pool times `league.payout_bps[",
        "prize_index]`. Idempotent per prize: a second call for the same index sees",
        "`paid[index] == true` and refuses. When the last unpaid prize is paid, the",
        "league is marked settled and its deposited total zeroed."
      ],
      "discriminator": [
        199,
        184,
        58,
        151,
        237,
        193,
        169,
        220
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "League"
              }
            ]
          }
        },
        {
          "name": "standings",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  116,
                  97,
                  110,
                  100,
                  105,
                  110,
                  103,
                  115
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "winner_membership",
          "docs": [
            "The prize winner, read from the frozen standings. Must be a member of this",
            "league (enforced by the membership account), so funds only go to someone",
            "who actually joined — the authority cannot redirect a prize to an outsider."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  101,
                  109,
                  98,
                  101,
                  114,
                  115,
                  104,
                  105,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "league"
              },
              {
                "kind": "account",
                "path": "winner"
              }
            ]
          }
        },
        {
          "name": "winner_token_account",
          "writable": true
        },
        {
          "name": "winner"
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "prize_index",
          "type": "u8"
        }
      ]
    },
    {
      "name": "post_final_standings",
      "docs": [
        "Freeze the league's final standings on-chain.",
        "",
        "This is the **single trusted input** to settlement. The `settle_authority`",
        "(the league creator at creation; rotatable to the Squads multisig per the",
        "owner's roadmap) signs, naming the five prize winners. Once written, the",
        "`FinalStandings` account is immutable, so the split that follows cannot be",
        "relitigated.",
        "",
        "The honest limitation, documented in issue #28: the winners come from an",
        "off-chain source (a fantasy score feed that is not yet on-chain). The",
        "program enforces everything *after* this point — the split math, the fee,",
        "that each winner was actually a member, and that settlement runs once —",
        "but it cannot itself verify that the standings are correct. A future",
        "on-chain score oracle would replace `settle_authority` with a",
        "program-derived signer, removing the one trusted key."
      ],
      "discriminator": [
        151,
        134,
        168,
        24,
        189,
        239,
        7,
        67
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "League"
              }
            ]
          }
        },
        {
          "name": "standings",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  116,
                  97,
                  110,
                  100,
                  105,
                  110,
                  103,
                  115
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "settle_authority",
          "docs": [
            "The single trusted signer for settlement. Set at league creation to the",
            "league creator; rotatable to the Squads multisig off-chain by creating a",
            "new league (the field is frozen like the rest)."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "winners",
          "type": {
            "array": [
              "pubkey",
              5
            ]
          }
        }
      ]
    },
    {
      "name": "refund_stake",
      "docs": [
        "Withdraw your own stake, unconditionally, once the timelock has passed.",
        "",
        "**This is the instruction that makes the rest safe to ship**, and the",
        "reason docs/BUILD-PLAN.md § D5 says to write it first. It turns \"the",
        "funds are gone\" into \"the funds are locked until a date\", whatever else",
        "in this program is broken, unfinished, or never written.",
        "",
        "So its conditions are deliberately minimal: the clock has passed, you",
        "deposited, you have not already been refunded. It does not consult",
        "league state, member count, settlement, or abandonment. **Every",
        "additional condition here is a new way for money to become permanently",
        "stuck** — which is precisely the failure this exists to make impossible.",
        "Do not add one."
      ],
      "discriminator": [
        185,
        80,
        20,
        3,
        110,
        92,
        178,
        240
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "League"
              }
            ]
          }
        },
        {
          "name": "membership",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  101,
                  109,
                  98,
                  101,
                  114,
                  115,
                  104,
                  105,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "league"
              },
              {
                "kind": "account",
                "path": "member"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "member_token_account",
          "writable": true
        },
        {
          "name": "member",
          "docs": [
            "Only the member themselves. A refund is not something anyone else may",
            "trigger on their behalf, however well-meant."
          ],
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    }
  ],
  "accounts": [
    {
      "name": "FinalStandings",
      "discriminator": [
        30,
        48,
        243,
        221,
        210,
        132,
        41,
        212
      ]
    },
    {
      "name": "League",
      "discriminator": [
        65,
        23,
        216,
        206,
        217,
        174,
        87,
        182
      ]
    },
    {
      "name": "Membership",
      "discriminator": [
        231,
        141,
        180,
        98,
        109,
        168,
        175,
        166
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "RulesHashMissing",
      "msg": "Rules hash is all zeroes; a league cannot take money without rules"
    },
    {
      "code": 6001,
      "name": "BuyInZero",
      "msg": "A pot league needs a buy-in; use initialize_free_league to play for nothing"
    },
    {
      "code": 6002,
      "name": "BuyInBelowMinimum",
      "msg": "Buy-in is below the minimum a pot is worth escrowing"
    },
    {
      "code": 6003,
      "name": "BuyInAboveCap",
      "msg": "Buy-in exceeds the cap for an unaudited escrow"
    },
    {
      "code": 6004,
      "name": "LeagueTooSmall",
      "msg": "A league needs at least two teams"
    },
    {
      "code": 6005,
      "name": "PayoutNotWhole",
      "msg": "Payout shares must sum to exactly 10000 basis points"
    },
    {
      "code": 6006,
      "name": "ChampionNotLargest",
      "msg": "The champion's share must be strictly the largest"
    },
    {
      "code": 6007,
      "name": "RefundUnlockNotInFuture",
      "msg": "Refund unlock time must be in the future"
    },
    {
      "code": 6008,
      "name": "RulesHashMismatch",
      "msg": "Accepted rules hash does not match the league's"
    },
    {
      "code": 6009,
      "name": "LeagueFull",
      "msg": "The league already has its full complement of teams"
    },
    {
      "code": 6010,
      "name": "AlreadyDeposited",
      "msg": "This member has already staked their buy-in"
    },
    {
      "code": 6011,
      "name": "AlreadyRefunded",
      "msg": "This stake has already been refunded"
    },
    {
      "code": 6012,
      "name": "NothingDeposited",
      "msg": "Nothing was staked, so there is nothing to refund"
    },
    {
      "code": 6013,
      "name": "RefundLocked",
      "msg": "The refund timelock has not passed yet"
    },
    {
      "code": 6014,
      "name": "WrongMint",
      "msg": "Token account is for a different mint than the league's pot"
    },
    {
      "code": 6015,
      "name": "NotTokenOwner",
      "msg": "Token account is not owned by the member"
    },
    {
      "code": 6016,
      "name": "MembershipLeagueMismatch",
      "msg": "Membership does not belong to this league"
    },
    {
      "code": 6017,
      "name": "MembershipMemberMismatch",
      "msg": "Membership does not belong to this member"
    },
    {
      "code": 6018,
      "name": "UnsupportedMintDecimals",
      "msg": "Pot tokens must have exactly six decimals"
    },
    {
      "code": 6019,
      "name": "FeeAboveCeiling",
      "msg": "Protocol fee is above the on-chain ceiling"
    },
    {
      "code": 6020,
      "name": "FeeRecipientMissing",
      "msg": "A non-zero fee requires a recipient"
    },
    {
      "code": 6021,
      "name": "LeagueHasNoPot",
      "msg": "This league plays for nothing and has no vault"
    },
    {
      "code": 6022,
      "name": "MathOverflow",
      "msg": "Arithmetic overflow"
    },
    {
      "code": 6023,
      "name": "WinnerNotMember",
      "msg": "A standings winner may not be the default pubkey"
    },
    {
      "code": 6024,
      "name": "AlreadySettled",
      "msg": "The league has already been settled"
    },
    {
      "code": 6025,
      "name": "NothingToSettle",
      "msg": "There is no stake to settle"
    },
    {
      "code": 6026,
      "name": "StandingsLeagueMismatch",
      "msg": "The frozen standings do not belong to this league"
    },
    {
      "code": 6027,
      "name": "StandingsMismatch",
      "msg": "A paid winner did not match the frozen standings"
    },
    {
      "code": 6028,
      "name": "FeeNotPaid",
      "msg": "The protocol fee must be paid before any prize"
    },
    {
      "code": 6029,
      "name": "InvalidPrizeIndex",
      "msg": "Prize index is out of range"
    }
  ],
  "types": [
    {
      "name": "FinalStandings",
      "docs": [
        "The frozen result of a league, posted once by the settle authority.",
        "",
        "Its existence freezes the five prize winners on-chain. After `post_final_",
        "standings` writes it, the `payout_fee` and `payout_prize` instructions read",
        "it and distribute the vault. It is immutable: the only mutations are the",
        "`fee_paid` and `paid` flags that mark each leg of settlement done, so the",
        "named winners cannot change and the pot cannot be paid twice."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "league",
            "type": "pubkey"
          },
          {
            "name": "winners",
            "docs": [
              "Prize winners in [`prize`] order: champion, runner-up, regular season,",
              "consolation, third place."
            ],
            "type": {
              "array": [
                "pubkey",
                5
              ]
            }
          },
          {
            "name": "fee_paid",
            "docs": [
              "Set once the protocol fee has been paid at settlement."
            ],
            "type": "bool"
          },
          {
            "name": "paid",
            "docs": [
              "Set once each prize has been paid. `settled` is true when all are set."
            ],
            "type": {
              "array": [
                "bool",
                5
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "InitializeFreeLeagueArgs",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "league_id",
            "type": {
              "array": [
                "u8",
                16
              ]
            }
          },
          {
            "name": "rules_hash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "max_teams",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "InitializeLeagueArgs",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "league_id",
            "type": {
              "array": [
                "u8",
                16
              ]
            }
          },
          {
            "name": "rules_hash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "buy_in",
            "type": "u64"
          },
          {
            "name": "refund_unlock_at",
            "type": "i64"
          },
          {
            "name": "payout_bps",
            "type": {
              "array": [
                "u16",
                5
              ]
            }
          },
          {
            "name": "fee_bps",
            "type": "u16"
          },
          {
            "name": "fee_recipient",
            "type": "pubkey"
          },
          {
            "name": "settle_authority",
            "type": "pubkey"
          },
          {
            "name": "max_teams",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "League",
      "docs": [
        "The terms of a league, frozen at creation.",
        "",
        "Deliberately absent: a commissioner authority. Nothing in this account may",
        "change, so there is nobody who needs the right to change it. Adding an",
        "authority field would create the exact attack docs/DECISIONS.md §",
        "\"Commissioner powers are bounded by the contract\" exists to remove."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "league_id",
            "docs": [
              "The league's UUID in Postgres, raw bytes. Also the PDA seed, so the",
              "off-chain record and the on-chain one address each other with no lookup",
              "table in between."
            ],
            "type": {
              "array": [
                "u8",
                16
              ]
            }
          },
          {
            "name": "rules_hash",
            "docs": [
              "SHA-256 of the canonically encoded rule set. The whole trust model."
            ],
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "token_mint",
            "docs": [
              "One token per league. Mixed pots are not a pot — docs/RULES.md § 7."
            ],
            "type": "pubkey"
          },
          {
            "name": "buy_in",
            "docs": [
              "Buy-in in the token's base units. Every member deposits exactly this."
            ],
            "type": "u64"
          },
          {
            "name": "refund_unlock_at",
            "docs": [
              "Unix seconds after which any member may withdraw their own stake",
              "unilaterally, whatever else is broken or unbuilt."
            ],
            "type": "i64"
          },
          {
            "name": "payout_bps",
            "docs": [
              "Payout split in basis points, indexed by [`prize`]. Sums to 10000 for a",
              "pot league; all zeroes for a free one."
            ],
            "type": {
              "array": [
                "u16",
                5
              ]
            }
          },
          {
            "name": "fee_bps",
            "docs": [
              "Protocol fee in basis points, taken once at settlement from the pot,",
              "before the payout split is applied.",
              "",
              "Frozen here with everything else, and part of the hashed rule set members",
              "sign — a fee we could change after the fact would make the immutability",
              "claim untrue of the one party with the most to gain from breaking it.",
              "**Never charged on a timelock refund**; see [`rostr_escrow::refund_stake`]."
            ],
            "type": "u16"
          },
          {
            "name": "fee_recipient",
            "docs": [
              "Where the fee is paid at settlement. `default()` when `fee_bps` is zero."
            ],
            "type": "pubkey"
          },
          {
            "name": "settle_authority",
            "docs": [
              "Who may post the league's final standings. The single trusted input to",
              "settlement: this key signs `post_final_standings`, which freezes the five",
              "prize winners on-chain. Everything downstream of that — the split math,",
              "the fee, the per-winner membership checks, idempotency — is enforced by",
              "the program, not by trust.",
              "",
              "Set at creation to the league creator; the owner's roadmap rotates it to",
              "the Squads multisig (docs/SETUP-REQUIRED.md) so that no individual",
              "person can unilaterally name the winners. It is a frozen field like the",
              "rest, so the rotation is a new league, not an edited one. A future",
              "on-chain score feed (the trustless oracle) would replace this signer with",
              "a program-derived one."
            ],
            "type": "pubkey"
          },
          {
            "name": "has_pot",
            "docs": [
              "False for a league that plays for nothing: no vault, no deposits, but its",
              "rules hash is anchored here exactly like a pot league's."
            ],
            "type": "bool"
          },
          {
            "name": "max_teams",
            "type": "u8"
          },
          {
            "name": "member_count",
            "type": "u8"
          },
          {
            "name": "total_deposited",
            "docs": [
              "Running total of live deposits, in base units. Decreases on refund, so",
              "it tracks what the vault actually holds rather than what it ever held."
            ],
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "Membership",
      "docs": [
        "One member's place in one league.",
        "",
        "Its existence *is* the consent record: it can only be created by",
        "`join_league`, which requires a matching rules hash."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "league",
            "type": "pubkey"
          },
          {
            "name": "member",
            "type": "pubkey"
          },
          {
            "name": "deposited",
            "docs": [
              "Base units staked. Zero until `deposit`."
            ],
            "type": "u64"
          },
          {
            "name": "refunded",
            "docs": [
              "Set once the stake has been withdrawn under the timelock."
            ],
            "type": "bool"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ]
};
