// Generated by `pnpm idl:sync` from target/types/rostr_escrow.ts.
//
// Do not edit by hand. This is the program's interface as the toolchain emitted
// it; editing it here would make the client disagree with the deployed program
// while looking perfectly reasonable in review.

/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/rostr_escrow.json`.
 */
export type RostrEscrow = {
  "address": "FtXXoS8G6N3dmhijp2kZGpmX6GmNtDk6cGj9h7eoK5NC",
  "metadata": {
    "name": "rostrEscrow",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Escrow for rostr league pots — deposits, timelock refund, and settlement"
  },
  "instructions": [
    {
      "name": "deposit",
      "docs": [
        "Stake the buy-in.",
        "",
        "Takes no amount. The figure is `league.buy_in` and nothing else, so",
        "\"everyone deposits the identical amount\" (docs/RULES.md § 7) is",
        "structural rather than a check that could be reordered away. A member",
        "who wants to stake more has no instruction that lets them."
      ],
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "league"
              }
            ]
          }
        },
        {
          "name": "membership",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  101,
                  109,
                  98,
                  101,
                  114,
                  115,
                  104,
                  105,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "league"
              },
              {
                "kind": "account",
                "path": "member"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "memberTokenAccount",
          "docs": [
            "The member's own token account. Constraining the mint here is what",
            "BUILD-PLAN calls rejecting mixed tokens \"at the type level\": a deposit in",
            "the wrong token fails account resolution before any handler runs."
          ],
          "writable": true
        },
        {
          "name": "member",
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "initializeFreeLeague",
      "docs": [
        "Anchor the rules of a league that plays for nothing.",
        "",
        "A free league has no vault, no buy-in, and no payout — but its rule set",
        "is hashed on-chain exactly like a pot league's, and members accept it the",
        "same way through `join_league`. That is the point: \"the rules are",
        "immutable and you can verify them\" has to be true of every league, not",
        "only the ones with money in them. Otherwise a free league's guarantee is",
        "our database, which is the thing this project exists not to ask anyone to",
        "trust.",
        "",
        "Separate from `initialize_league` rather than a flag on it because the",
        "account set genuinely differs: there is no mint and no vault to create,",
        "and making them optional would mean a caller could pass `None` to a pot",
        "league and get a league that can never take a deposit."
      ],
      "discriminator": [
        45,
        128,
        109,
        8,
        49,
        140,
        174,
        112
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "arg",
                "path": "args.league_id"
              }
            ]
          }
        },
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "args",
          "type": {
            "defined": {
              "name": "initializeFreeLeagueArgs"
            }
          }
        }
      ]
    },
    {
      "name": "initializeLeague",
      "docs": [
        "Create the on-chain record of a league, freeze its terms, and open its",
        "vault.",
        "",
        "Everything validated here is validated again off-chain by",
        "`validateRules()` before a league is written to Postgres. The duplication",
        "is deliberate: the off-chain check produces good error messages for a",
        "league creator, and this one is what actually binds, because it is the",
        "only one an attacker cannot skip by calling the program directly."
      ],
      "discriminator": [
        222,
        3,
        239,
        48,
        195,
        8,
        143,
        93
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "arg",
                "path": "args.league_id"
              }
            ]
          }
        },
        {
          "name": "mint"
        },
        {
          "name": "vault",
          "docs": [
            "The pot. A PDA token account whose authority is the league PDA, so no",
            "key held by any person can move what is in it — only this program can,",
            "and only through the instructions below."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "payer",
          "docs": [
            "Pays rent, and is recorded as `league.commissioner`.",
            "",
            "This used to say the key held no privileges afterwards and was not",
            "recorded. It is now recorded, and it holds exactly one: `start_season`.",
            "That instruction changes no term and moves no token — see the field."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "args",
          "type": {
            "defined": {
              "name": "initializeLeagueArgs"
            }
          }
        }
      ]
    },
    {
      "name": "joinLeague",
      "docs": [
        "Join a league by accepting its rules hash.",
        "",
        "The caller passes the hash **they** believe they are agreeing to, and",
        "the program requires it to equal the league's. That is what makes",
        "consent provable rather than asserted: a client that displayed one rule",
        "set cannot enrol someone under another, because the signature is over a",
        "transaction naming the hash. A boolean \"I agree\" would prove only that",
        "somebody clicked something."
      ],
      "discriminator": [
        32,
        4,
        179,
        25,
        65,
        34,
        15,
        127
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "league"
              }
            ]
          }
        },
        {
          "name": "membership",
          "docs": [
            "Seeded by league and member, so one member cannot hold two places in the",
            "same league: the second `join_league` collides with an existing account",
            "rather than needing a check that could be forgotten."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  101,
                  109,
                  98,
                  101,
                  114,
                  115,
                  104,
                  105,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "league"
              },
              {
                "kind": "account",
                "path": "member"
              }
            ]
          }
        },
        {
          "name": "member",
          "writable": true,
          "signer": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "rulesHash",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "refundStake",
      "docs": [
        "Withdraw your own stake, unconditionally, once the timelock has passed.",
        "",
        "**This is the instruction that makes the rest safe to ship**, and the",
        "reason docs/BUILD-PLAN.md § D5 says to write it first. It turns \"the",
        "funds are gone\" into \"the funds are locked until a date\", whatever else",
        "in this program is broken, unfinished, or never written.",
        "",
        "So its conditions are deliberately minimal: the clock has passed, you",
        "deposited, you have not already been refunded. It does not consult",
        "league state, member count, settlement, or abandonment. **Every",
        "additional condition here is a new way for money to become permanently",
        "stuck** — which is precisely the failure this exists to make impossible.",
        "Do not add one."
      ],
      "discriminator": [
        185,
        80,
        20,
        3,
        110,
        92,
        178,
        240
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "league"
              }
            ]
          }
        },
        {
          "name": "membership",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  101,
                  109,
                  98,
                  101,
                  114,
                  115,
                  104,
                  105,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "league"
              },
              {
                "kind": "account",
                "path": "member"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "league"
              }
            ]
          }
        },
        {
          "name": "memberTokenAccount",
          "writable": true
        },
        {
          "name": "member",
          "docs": [
            "Only the member themselves. A refund is not something anyone else may",
            "trigger on their behalf, however well-meant."
          ],
          "signer": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "startSeason",
      "docs": [
        "Declare that this league's season has begun, closing the failed-league",
        "refund.",
        "",
        "## What this is for",
        "",
        "A league that is not ready at its draft time — short of its buy-ins, or",
        "with an odd field — must give everyone their money back **then**, not in",
        "six months. But this program cannot tell a failed league from a running",
        "one: the roster, the draft and who has paid are Postgres facts, and",
        "`rules_hash` is 32 opaque bytes to it. Something has to say so.",
        "",
        "So the default is failure. A league that was ready calls this inside its",
        "grace window; a league that was not never does, and its members are",
        "released automatically. **Doing nothing returns the money.**",
        "",
        "## The window is the whole safety argument",
        "",
        "This is illegal from exactly the instant the failed-league refund becomes",
        "legal, so the two can never both be available. A league therefore cannot",
        "be started with a partly-drained vault, and a member cannot be refunded",
        "out of a season that has begun — the halves are complements rather than",
        "two checks that have to agree with each other.",
        "",
        "## What it cannot do",
        "",
        "It changes no term, moves no token, and names no winner. Its only effect",
        "is which of two refund schedules the members are on, and both of those",
        "end with the member holding their own money. `drawDraftOrder` refuses to",
        "draw a pot league until this has landed, which is what stops a",
        "commissioner running a season with the escape hatch still open.",
        "",
        "Free leagues are excluded rather than exempted: no vault, so nothing to",
        "release and nothing to protect."
      ],
      "discriminator": [
        152,
        173,
        197,
        144,
        221,
        79,
        236,
        62
      ],
      "accounts": [
        {
          "name": "league",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  101,
                  97,
                  103,
                  117,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "league.league_id",
                "account": "league"
              }
            ]
          }
        },
        {
          "name": "commissioner",
          "docs": [
            "The wallet that created the league. No other key can start a season, and",
            "this one can do nothing else."
          ],
          "signer": true
        }
      ],
      "args": []
    }
  ],
  "accounts": [
    {
      "name": "league",
      "discriminator": [
        65,
        23,
        216,
        206,
        217,
        174,
        87,
        182
      ]
    },
    {
      "name": "membership",
      "discriminator": [
        231,
        141,
        180,
        98,
        109,
        168,
        175,
        166
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "rulesHashMissing",
      "msg": "Rules hash is all zeroes; a league cannot take money without rules"
    },
    {
      "code": 6001,
      "name": "buyInZero",
      "msg": "A pot league needs a buy-in; use initialize_free_league to play for nothing"
    },
    {
      "code": 6002,
      "name": "buyInBelowMinimum",
      "msg": "Buy-in is below the minimum a pot is worth escrowing"
    },
    {
      "code": 6003,
      "name": "buyInAboveCap",
      "msg": "Buy-in exceeds the cap for an unaudited escrow"
    },
    {
      "code": 6004,
      "name": "leagueTooSmall",
      "msg": "A league needs at least two teams"
    },
    {
      "code": 6005,
      "name": "payoutNotWhole",
      "msg": "Payout shares must sum to exactly 10000 basis points"
    },
    {
      "code": 6006,
      "name": "championNotLargest",
      "msg": "The champion's share must be strictly the largest"
    },
    {
      "code": 6007,
      "name": "refundUnlockNotInFuture",
      "msg": "Refund unlock time must be in the future"
    },
    {
      "code": 6008,
      "name": "rulesHashMismatch",
      "msg": "Accepted rules hash does not match the league's"
    },
    {
      "code": 6009,
      "name": "leagueFull",
      "msg": "The league already has its full complement of teams"
    },
    {
      "code": 6010,
      "name": "alreadyDeposited",
      "msg": "This member has already staked their buy-in"
    },
    {
      "code": 6011,
      "name": "alreadyRefunded",
      "msg": "This stake has already been refunded"
    },
    {
      "code": 6012,
      "name": "nothingDeposited",
      "msg": "Nothing was staked, so there is nothing to refund"
    },
    {
      "code": 6013,
      "name": "refundLocked",
      "msg": "The refund timelock has not passed yet"
    },
    {
      "code": 6014,
      "name": "wrongMint",
      "msg": "Token account is for a different mint than the league's pot"
    },
    {
      "code": 6015,
      "name": "notTokenOwner",
      "msg": "Token account is not owned by the member"
    },
    {
      "code": 6016,
      "name": "membershipLeagueMismatch",
      "msg": "Membership does not belong to this league"
    },
    {
      "code": 6017,
      "name": "membershipMemberMismatch",
      "msg": "Membership does not belong to this member"
    },
    {
      "code": 6018,
      "name": "unsupportedMintDecimals",
      "msg": "Pot tokens must have exactly six decimals"
    },
    {
      "code": 6019,
      "name": "feeAboveCeiling",
      "msg": "Protocol fee is above the on-chain ceiling"
    },
    {
      "code": 6020,
      "name": "feeRecipientMissing",
      "msg": "A non-zero fee requires a recipient"
    },
    {
      "code": 6021,
      "name": "leagueHasNoPot",
      "msg": "This league plays for nothing and has no vault"
    },
    {
      "code": 6022,
      "name": "mathOverflow",
      "msg": "Arithmetic overflow"
    },
    {
      "code": 6023,
      "name": "refundUnlockTooFar",
      "msg": "Refund unlock time is too far in the future"
    },
    {
      "code": 6024,
      "name": "notCommissioner",
      "msg": "Only the wallet that created this league may start its season"
    },
    {
      "code": 6025,
      "name": "alreadyStarted",
      "msg": "This league's season has already started"
    },
    {
      "code": 6026,
      "name": "startWindowClosed",
      "msg": "The window to start this season has closed; its members may now be refunded"
    },
    {
      "code": 6027,
      "name": "startDeadlineNotInFuture",
      "msg": "The start deadline must be in the future"
    },
    {
      "code": 6028,
      "name": "startDeadlineAfterRefundUnlock",
      "msg": "The start deadline must fall before the refund unlock"
    },
    {
      "code": 6029,
      "name": "leagueTooLarge",
      "msg": "A league may have at most twelve teams; above that it could never be settled"
    },
    {
      "code": 6030,
      "name": "noTiebreakers",
      "msg": "Seeding requires at least one tiebreaker"
    },
    {
      "code": 6031,
      "name": "tiebreakersExhausted",
      "msg": "Tiebreakers were exhausted with teams still tied; the chain must end in a deterministic one"
    },
    {
      "code": 6032,
      "name": "unknownTeam",
      "msg": "A result names a team that is not in this league"
    },
    {
      "code": 6033,
      "name": "unknownTiebreaker",
      "msg": "Unknown tiebreaker discriminant"
    },
    {
      "code": 6034,
      "name": "tooManyTeams",
      "msg": "More teams than this program can settle"
    },
    {
      "code": 6035,
      "name": "malformedSchedule",
      "msg": "Two results occupy the same week and team"
    },
    {
      "code": 6036,
      "name": "fieldTooSmall",
      "msg": "A bracket needs at least two teams and fewer byes than teams"
    },
    {
      "code": 6037,
      "name": "notEnoughWeeks",
      "msg": "This field needs more weeks than the bracket window has"
    },
    {
      "code": 6038,
      "name": "bracketInvariant",
      "msg": "The playoff ladder reached a state it should not be able to reach"
    }
  ],
  "types": [
    {
      "name": "initializeFreeLeagueArgs",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "leagueId",
            "type": {
              "array": [
                "u8",
                16
              ]
            }
          },
          {
            "name": "rulesHash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "maxTeams",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "initializeLeagueArgs",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "leagueId",
            "type": {
              "array": [
                "u8",
                16
              ]
            }
          },
          {
            "name": "rulesHash",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "buyIn",
            "type": "u64"
          },
          {
            "name": "refundUnlockAt",
            "type": "i64"
          },
          {
            "name": "payoutBps",
            "type": {
              "array": [
                "u16",
                5
              ]
            }
          },
          {
            "name": "feeBps",
            "type": "u16"
          },
          {
            "name": "feeRecipient",
            "type": "pubkey"
          },
          {
            "name": "maxTeams",
            "type": "u8"
          },
          {
            "name": "startDeadline",
            "docs": [
              "When the season must be declared started by. Appended, so the argument",
              "order is stable. See the field on `League`."
            ],
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "league",
      "docs": [
        "The terms of a league, frozen at creation.",
        "",
        "**No term may change, and there is no authority that could change one.** That",
        "is what docs/DECISIONS.md § \"Commissioner powers are bounded by the contract\"",
        "asks for, and it still holds: the buy-in, the fee, its recipient, the payout",
        "split, the mint and the refund date are written once and read forever.",
        "",
        "This paragraph used to say the account had no authority field at all. It has",
        "one — `commissioner`, whose sole power is `start_season`, and whose sole",
        "effect is which of two refund schedules a member is on. Both end with them",
        "holding their own money. See the field for why that was the least bad way to",
        "let a league that never started give the money back."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "leagueId",
            "docs": [
              "The league's UUID in Postgres, raw bytes. Also the PDA seed, so the",
              "off-chain record and the on-chain one address each other with no lookup",
              "table in between."
            ],
            "type": {
              "array": [
                "u8",
                16
              ]
            }
          },
          {
            "name": "rulesHash",
            "docs": [
              "SHA-256 of the canonically encoded rule set. The whole trust model."
            ],
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "tokenMint",
            "docs": [
              "One token per league. Mixed pots are not a pot — docs/RULES.md § 7."
            ],
            "type": "pubkey"
          },
          {
            "name": "buyIn",
            "docs": [
              "Buy-in in the token's base units. Every member deposits exactly this."
            ],
            "type": "u64"
          },
          {
            "name": "refundUnlockAt",
            "docs": [
              "Unix seconds after which any member may withdraw their own stake",
              "unilaterally, whatever else is broken or unbuilt."
            ],
            "type": "i64"
          },
          {
            "name": "payoutBps",
            "docs": [
              "Payout split in basis points, indexed by [`prize`]. Sums to 10000 for a",
              "pot league; all zeroes for a free one."
            ],
            "type": {
              "array": [
                "u16",
                5
              ]
            }
          },
          {
            "name": "feeBps",
            "docs": [
              "Protocol fee in basis points, taken once at settlement from the pot,",
              "before the payout split is applied.",
              "",
              "Frozen here with everything else, and part of the hashed rule set members",
              "sign — a fee we could change after the fact would make the immutability",
              "claim untrue of the one party with the most to gain from breaking it.",
              "**Never charged on a timelock refund**; see [`rostr_escrow::refund_stake`]."
            ],
            "type": "u16"
          },
          {
            "name": "feeRecipient",
            "docs": [
              "Where the fee is paid at settlement. `default()` when `fee_bps` is zero."
            ],
            "type": "pubkey"
          },
          {
            "name": "hasPot",
            "docs": [
              "False for a league that plays for nothing: no vault, no deposits, but its",
              "rules hash is anchored here exactly like a pot league's."
            ],
            "type": "bool"
          },
          {
            "name": "maxTeams",
            "type": "u8"
          },
          {
            "name": "memberCount",
            "type": "u8"
          },
          {
            "name": "totalDeposited",
            "docs": [
              "Running total of live deposits, in base units. Decreases on refund, so",
              "it tracks what the vault actually holds rather than what it ever held."
            ],
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "commissioner",
            "type": "pubkey"
          },
          {
            "name": "startDeadline",
            "type": "i64"
          },
          {
            "name": "started",
            "type": "bool"
          }
        ]
      }
    },
    {
      "name": "membership",
      "docs": [
        "One member's place in one league.",
        "",
        "Its existence *is* the consent record: it can only be created by",
        "`join_league`, which requires a matching rules hash."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "league",
            "type": "pubkey"
          },
          {
            "name": "member",
            "type": "pubkey"
          },
          {
            "name": "deposited",
            "docs": [
              "Base units staked. Zero until `deposit`."
            ],
            "type": "u64"
          },
          {
            "name": "refunded",
            "docs": [
              "Set once the stake has been withdrawn under the timelock."
            ],
            "type": "bool"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ]
};
