/**
 * The bracket conformance corpus — the shared spec for two implementations of
 * the playoff ladder.
 *
 * Same argument as `cases.ts`, one step further down the chain that decides who
 * is paid. `computeStandings` produces the seeds; `buildBracket` turns the seeds
 * and the playoff scores into a champion and a runner-up, which between them
 * hold 90% of the default payout. Settlement cannot call TypeScript, so the walk
 * has to exist twice — and **two implementations of one rule is the failure that
 * pays the wrong person while every test is green.**
 *
 * Neither side is the authority. `bracket-corpus.json` is, it is generated by
 * running `buildBracket`, and both consume it.
 *
 * ## What is pinned, and what deliberately is not
 *
 * Pinned: every game's pairing, its winner, whether a tie sent the higher seed
 * through, which teams took a bye, who survived each round, and the three
 * outcomes settlement reads — champion, runner-up, third place.
 *
 * Not pinned: `label`. "Semifinal" and "Quarterfinal" exist to render a screen,
 * and requiring the on-chain kernel to carry strings to satisfy a conformance
 * test would put display text in a program that has no display.
 *
 * ## The cases are chosen for where a reimplementation goes wrong
 *
 * Not for coverage of the happy path, which one fixture would give. Each case
 * says why it exists, and the `why` is carried into the JSON so the Rust side
 * reads it too.
 */

import type { MatchupResult } from "../standings.js";
import { TEAM } from "./cases.js";

export interface BracketCase {
  readonly name: string;
  readonly why: string;
  /** The field in seed order, best first. Seeds are positions in this array. */
  readonly field: readonly string[];
  readonly weeks: readonly number[];
  readonly firstRoundByes: number;
  readonly results: readonly MatchupResult[];
  readonly thirdPlace: boolean;
}

/** A played game. Points are milli-points, as everywhere else. */
const game = (
  week: number,
  home: string,
  away: string,
  homeMilliPoints: number,
  awayMilliPoints: number,
): MatchupResult => ({
  week,
  homeTeamId: home,
  awayTeamId: away,
  homeMilliPoints,
  awayMilliPoints,
});

const [T1, T2, T3, T4, T5, T6, T7, T8] = TEAM as unknown as [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];

export const BRACKET_CASES: readonly BracketCase[] = [
  {
    name: "four teams, two rounds, played out",
    why: "The base case. Round one pairs 1v4 and 2v3; whoever wins meets in the final. Everything else here is a deviation from this shape, so if this is wrong nothing below means anything.",
    field: [T1, T2, T3, T4],
    weeks: [16, 17],
    firstRoundByes: 0,
    results: [
      game(16, T1, T4, 110_000, 100_000),
      game(16, T2, T3, 90_000, 95_000),
      game(17, T1, T3, 120_000, 118_000),
    ],
    thirdPlace: false,
  },
  {
    name: "six teams with two byes — the default playoff shape",
    why: "`playoffTeams: 6` with `byeSeeds: 2` is what a default league actually plays, so a kernel that only handles powers of two is wrong for the common case rather than for an edge.",
    field: [T1, T2, T3, T4, T5, T6],
    weeks: [15, 16, 17],
    firstRoundByes: 2,
    results: [
      game(15, T3, T6, 100_000, 90_000),
      game(15, T4, T5, 88_000, 99_000),
      game(16, T1, T5, 105_000, 101_000),
      game(16, T2, T3, 97_000, 99_000),
      game(17, T1, T3, 130_000, 121_000),
    ],
    thirdPlace: false,
  },
  {
    name: "every round reseeds, so an upset changes who the top seed meets",
    why: "The discriminating case against a fixed ladder. Seed 8 beats seed 1 in round one; the survivors are 2, 3, 4 and 8, so reseeding pairs 2v8 and 3v4. A fixed ladder would carry 8 into seed 1's slot and pair 8v4 and 2v3 — different games, and eventually a different champion.",
    field: [T1, T2, T3, T4, T5, T6, T7, T8],
    weeks: [15, 16, 17],
    firstRoundByes: 0,
    results: [
      game(15, T1, T8, 90_000, 95_000),
      game(15, T2, T7, 110_000, 100_000),
      game(15, T3, T6, 105_000, 99_000),
      game(15, T4, T5, 102_000, 98_000),
      game(16, T2, T8, 115_000, 110_000),
      game(16, T3, T4, 108_000, 112_000),
      game(17, T2, T4, 125_000, 120_000),
    ],
    thirdPlace: false,
  },
  {
    name: "equal points send the higher seed through",
    why: "The one place bracket scoring differs from the regular season, where a tie is a real outcome both teams keep. `RULES.md` §5 advances the higher seed, and `decidedBySeed` has to say so — a bracket game that looks like an ordinary win when it was a coin-flip on seeding is a screen lying to the loser.",
    field: [T1, T2, T3, T4],
    weeks: [16, 17],
    firstRoundByes: 0,
    results: [
      game(16, T1, T4, 100_000, 100_000),
      game(16, T2, T3, 100_000, 100_000),
      game(17, T1, T2, 111_000, 111_000),
    ],
    thirdPlace: false,
  },
  {
    name: "the ladder stops at the first round holding an unscored game",
    why: "Who plays next genuinely is not known yet, so the round must not be invented. A kernel that padded the remaining rounds with empty games would derive a champion from a season that has not finished.",
    field: [T1, T2, T3, T4],
    weeks: [16, 17],
    firstRoundByes: 0,
    results: [game(16, T1, T4, 110_000, 100_000)],
    thirdPlace: false,
  },
  {
    name: "half-scored semifinals produce no third-place game",
    why: "The trap `buildThirdPlace` documents. The ladder stops at the semifinal, so the second-to-last round *built* is the quarterfinal — pairing its losers would invent a third-place game between two teams knocked out a round earlier. The semifinal is found by round number, never by taking the last round built.",
    field: [T1, T2, T3, T4, T5, T6, T7, T8],
    weeks: [15, 16, 17],
    firstRoundByes: 0,
    results: [
      game(15, T1, T8, 110_000, 100_000),
      game(15, T2, T7, 110_000, 100_000),
      game(15, T3, T6, 110_000, 100_000),
      game(15, T4, T5, 110_000, 100_000),
      game(16, T1, T4, 105_000, 100_000),
    ],
    thirdPlace: true,
  },
  {
    name: "third place is played in the championship week by the losing semifinalists",
    why: "It is a prize, not a step: nobody advances out of it, so it sits beside the ladder rather than in it. The higher seed is home, and the pairing is the two semifinal losers — not the two teams that happen to be left over.",
    field: [T1, T2, T3, T4],
    weeks: [16, 17],
    firstRoundByes: 0,
    results: [
      game(16, T1, T4, 110_000, 100_000),
      game(16, T2, T3, 90_000, 95_000),
      game(17, T1, T3, 120_000, 118_000),
      game(17, T2, T4, 101_000, 99_000),
    ],
    thirdPlace: true,
  },
  {
    name: "third place is not built when the league does not play it",
    why: "The negative control for the case above. `thirdPlace: false` must yield no game even when the semifinals resolved and the fixture for it exists in the results — otherwise a league that never agreed to the prize would have a holder derived for it.",
    field: [T1, T2, T3, T4],
    weeks: [16, 17],
    firstRoundByes: 0,
    results: [
      game(16, T1, T4, 110_000, 100_000),
      game(16, T2, T3, 90_000, 95_000),
      game(17, T1, T3, 120_000, 118_000),
      game(17, T2, T4, 101_000, 99_000),
    ],
    thirdPlace: false,
  },
  {
    name: "a bracket plays the last weeks of its window, not the first",
    why: "A four-team bracket in a three-week window plays 16 and 17. It must finish in the championship week because that is the week the payout settles — and the week-15 result below is a real fixture between the same two teams that must be ignored entirely.",
    field: [T1, T2, T3, T4],
    weeks: [15, 16, 17],
    firstRoundByes: 0,
    results: [
      game(15, T1, T4, 10_000, 200_000),
      game(16, T1, T4, 110_000, 100_000),
      game(16, T2, T3, 95_000, 90_000),
      game(17, T1, T2, 120_000, 118_000),
    ],
    thirdPlace: false,
  },
  {
    name: "a stored result is found whichever way round it is recorded",
    why: "Which team a stored row calls home is the database's business; a bracket game is looked up by its pair. The points must still attribute by the *result's* own orientation — reading them positionally instead would hand every reversed row's score to the wrong team.",
    field: [T1, T2, T3, T4],
    weeks: [16, 17],
    firstRoundByes: 0,
    results: [
      game(16, T4, T1, 100_000, 110_000),
      game(16, T3, T2, 95_000, 90_000),
      game(17, T3, T1, 118_000, 120_000),
    ],
    thirdPlace: false,
  },
  {
    name: "five teams with three byes",
    why: "Exercises `byesNeeded` in a later round rather than the signed first-round count: one game in round one, then four alive and none needed. A kernel that applied the first-round bye count to every round would sit the top three out twice.",
    field: [T1, T2, T3, T4, T5],
    weeks: [15, 16, 17],
    firstRoundByes: 3,
    results: [
      game(15, T4, T5, 90_000, 100_000),
      game(16, T1, T5, 110_000, 100_000),
      game(16, T2, T3, 95_000, 99_000),
      game(17, T1, T3, 130_000, 125_000),
    ],
    thirdPlace: false,
  },
  {
    name: "two teams, one week",
    why: "The smallest legal bracket, and the boundary `FIELD_TOO_SMALL` sits directly above. A kernel with an off-by-one in the field check refuses this or accepts a field of one.",
    field: [T1, T2],
    weeks: [17],
    firstRoundByes: 0,
    results: [game(17, T1, T2, 120_000, 118_000)],
    thirdPlace: false,
  },
  {
    name: "a field of one is refused",
    why: "A one-team bracket has no game to play and would otherwise crown its only entrant unopposed. This is reachable: nothing ties `playoffTeams` to how many people actually joined.",
    field: [T1],
    weeks: [17],
    firstRoundByes: 0,
    results: [],
    thirdPlace: false,
  },
  {
    name: "a bye count equal to the field is refused",
    why: "Every team sitting out leaves no game and no way to eliminate anyone. The bound is `0 <= byes < field.length`, and the upper end is the half a plausible implementation gets wrong.",
    field: [T1, T2, T3, T4],
    weeks: [16, 17],
    firstRoundByes: 4,
    results: [],
    thirdPlace: false,
  },
  {
    name: "a window too short for the field is refused",
    why: "Eight teams need three rounds. Refusing is right and the alternative is worse than it looks — truncating to the weeks available would crown whoever happened to be leading when the window ran out.",
    field: [T1, T2, T3, T4, T5, T6, T7, T8],
    weeks: [16, 17],
    firstRoundByes: 0,
    results: [],
    thirdPlace: false,
  },
  {
    name: "an odd number left to pair is an invariant failure, not a league's problem",
    why: "Five teams with no byes leaves five to pair. `INVARIANT` rather than `FIELD_TOO_SMALL` is the whole point of the distinction: this is our bug in the ladder that decides who is paid, and it must never be filed under that league's problem and forgotten.",
    field: [T1, T2, T3, T4, T5],
    weeks: [15, 16, 17],
    firstRoundByes: 0,
    results: [],
    thirdPlace: false,
  },
];
