#!/usr/bin/env node
/**
 * Copy the built IDL into `@rostr/escrow` as a TypeScript module.
 *
 * `anchor build` writes `target/idl/rostr_escrow.json`, and `target/` is
 * gitignored — correctly, it is build output. But the web app has to know the
 * program's interface, and neither Vercel nor the TypeScript CI job has a Rust
 * toolchain to produce it. So the IDL is committed into the package, and this
 * script is what keeps the copy honest.
 *
 *   pnpm idl:sync        regenerate after changing the program
 *   pnpm idl:check       fail if the committed copy is stale
 *
 * The Anchor CI job runs the check after building, which is the only place the
 * two can be compared — so a program change that forgets to sync fails there
 * rather than shipping a client that calls instructions the program does not
 * have.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = join(process.cwd(), "target", "idl", "rostr_escrow.json");
const OUT = join(process.cwd(), "packages", "escrow", "src", "idl.ts");

const HEADER = `// Generated by \`pnpm idl:sync\` from target/idl/rostr_escrow.json.
//
// Do not edit by hand. This is the program's interface as the toolchain emitted
// it; editing it here would make the client disagree with the deployed program
// while looking perfectly reasonable in review.

/**
 * A deliberately shallow type. The full IDL shape is large and recursive, and
 * spelling it out would cost compile time to describe something Anchor already
 * validates at runtime. Consumers cast to Anchor's \`Idl\` at the boundary.
 */
export type EscrowIdl = {
  readonly address: string;
  readonly metadata: {
    readonly name: string;
    readonly version: string;
    readonly spec: string;
    // Anchor also emits \`description\` from Cargo.toml, and may add more. An
    // index signature keeps a future field from failing the build over
    // something this type does not need to know about.
    readonly [key: string]: unknown;
  };
  readonly instructions: readonly unknown[];
  readonly accounts: readonly unknown[];
  readonly errors: readonly unknown[];
  readonly types: readonly unknown[];
};

export const ESCROW_IDL: EscrowIdl = `;

function render() {
  const idl = JSON.parse(readFileSync(SOURCE, "utf8"));
  return `${HEADER}${JSON.stringify(idl, null, 2)};\n`;
}

const check = process.argv.includes("--check");
const next = render();

if (check) {
  const current = readFileSync(OUT, "utf8");
  if (current !== next) {
    console.error(
      "The committed IDL is stale.\n" +
        "  packages/escrow/src/idl.ts does not match target/idl/rostr_escrow.json.\n" +
        "  Run `pnpm idl:sync` and commit the result.",
    );
    process.exit(1);
  }
  console.log("IDL is in sync.");
} else {
  writeFileSync(OUT, next);
  console.log(`Wrote ${OUT}`);
}
