#!/usr/bin/env node
/**
 * Copy the built IDL and its TypeScript type into `@rostr/escrow`.
 *
 * `anchor build` writes both into `target/`, and `target/` is gitignored —
 * correctly, it is build output. But the web app has to know the program's
 * interface, and neither Vercel nor the TypeScript CI job has a Rust toolchain
 * to produce it. So both are committed into the package, and this script is what
 * keeps the copies honest.
 *
 *   pnpm idl:sync        regenerate after changing the program
 *   pnpm idl:check       fail if either committed copy is stale
 *
 * The Anchor CI job runs the check after building, which is the only place the
 * halves can be compared — so a program change that forgets to sync fails there
 * rather than shipping a client that calls instructions the program does not
 * have.
 *
 * Two files rather than one because they do different jobs. The JSON is the
 * runtime value Anchor's `Program` needs; the `.ts` is a type, and it is what
 * makes `program.methods.deposit()` a compile error when the instruction is
 * renamed instead of a runtime failure holding someone's money.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const GENERATED = (source) =>
  `// Generated by \`pnpm idl:sync\` from ${source}.
//
// Do not edit by hand. This is the program's interface as the toolchain emitted
// it; editing it here would make the client disagree with the deployed program
// while looking perfectly reasonable in review.
`;

const IDL_TYPE = `
/**
 * A deliberately shallow type for the runtime value. The full shape is large and
 * recursive, and spelling it out would cost compile time to describe something
 * Anchor validates at runtime anyway — \`RostrEscrow\` in ./types.ts is the type
 * that actually earns its keep.
 */
export type EscrowIdl = {
  readonly address: string;
  readonly metadata: {
    readonly name: string;
    readonly version: string;
    readonly spec: string;
    readonly [key: string]: unknown;
  };
  readonly instructions: readonly unknown[];
  readonly accounts: readonly unknown[];
  readonly errors: readonly unknown[];
  readonly types: readonly unknown[];
};

export const ESCROW_IDL: EscrowIdl = `;

const TARGETS = [
  {
    source: join(process.cwd(), "target", "idl", "rostr_escrow.json"),
    out: join(process.cwd(), "packages", "escrow", "src", "idl.ts"),
    render(raw) {
      const idl = JSON.parse(raw);
      return `${GENERATED("target/idl/rostr_escrow.json")}${IDL_TYPE}${JSON.stringify(idl, null, 2)};\n`;
    },
  },
  {
    source: join(process.cwd(), "target", "types", "rostr_escrow.ts"),
    out: join(process.cwd(), "packages", "escrow", "src", "types.ts"),
    render(raw) {
      return `${GENERATED("target/types/rostr_escrow.ts")}\n${raw}`;
    },
  },
];

const check = process.argv.includes("--check");
let stale = false;

for (const target of TARGETS) {
  const next = target.render(readFileSync(target.source, "utf8"));

  if (check) {
    if (readFileSync(target.out, "utf8") !== next) {
      console.error(`STALE: ${target.out} does not match ${target.source}`);
      stale = true;
    }
  } else {
    writeFileSync(target.out, next);
    console.log(`Wrote ${target.out}`);
  }
}

if (check) {
  if (stale) {
    console.error("\nRun `pnpm idl:sync` and commit the result.");
    process.exit(1);
  }
  console.log("IDL and types are in sync.");
}
